#! /bin/sh

wmname LG3D
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor Settings
# bash ./monitor.sh


nitrogen --restore &
./.config/polybar/launch.sh & 
picom & 
dunst &
udiskie &
redshift & 

# Monitor setup
# bspc monitor DP-0 -d I II III IV V VI VII VIII IX X 
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX X 

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_frame_opacity 0.0

bspc rule -a Gimp desktop='^8'	state=floating follow=on
bspc rule -a Chromium			desktop='^2'
bspc rule -a mplayer2			state=floating
bspc rule -a Zathura			state=tiled
bspc rule -a Emacs				state=tiled
bspc rule -a Kupfer.py			focus=on
bspc rule -a Screenkey			manage=off
