# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/lyvxi6vw3s1a1khg58rg9dd2r793vxwx-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- e nvim
    abbr --add -- n ninja

    # Aliases
    alias .. 'cd ..'
    alias cat bat
    alias fistory 'history --show-time='\''%h/%d - %H:%M:%S '\'''
    alias gd 'git diff'
    alias gp 'git push'
    alias gpl 'git pull'
    alias gs 'git status'
    alias l 'eza -lh'
    alias ll 'eza -l'
    alias ls eza
    alias reload_fish 'source ~/.config/fish/config.fish'
    alias rmsym 'rm -i'
    alias softln 'ln -s'
    alias tmux 'tmux -2'
    alias vim nvim

    # Interactive shell initialisation
    /nix/store/zbdpsb4saxi3fj7n8zcdaprmfnvxbvw6-fzf-0.67.0/bin/fzf --fish | source

    /nix/store/15zj7wpihpsvnn932p7s71sc5jjvnp0n-zoxide-0.9.9/bin/zoxide init fish | source

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/dpatel/.local/share/fish/home-manager/generated_completions" $post
    end

    set __fish_git_prompt_showuntrackedfiles yes
    set __fish_git_prompt_showdirtystate yes
    set __fish_git_prompt_showstashstate ""
    set __fish_git_prompt_showupstream none
    set -g fish_prompt_pwd_dir_length 3

    # colored man output
    setenv LESS_TERMCAP_mb \e'[01;31m'
    setenv LESS_TERMCAP_md \e'[01;38;5;74m'
    setenv LESS_TERMCAP_me \e'[0m'
    setenv LESS_TERMCAP_se \e'[0m'
    setenv LESS_TERMCAP_so \e'[38;5;246m'
    setenv LESS_TERMCAP_ue \e'[0m'
    setenv LESS_TERMCAP_us \e'[04;38;5;146m'

    function fish_user_key_bindings
        bind \cz 'fg>/dev/null ^/dev/null'
        if functions -q fzf_key_bindings
            fzf_key_bindings
        end
    end

end
